inherit_gem:
  armitage-rubocop:
    - lib/rubocop.general.yml
    - lib/rubocop.rspec.yml
    - lib/rubocop.rake.yml

AllCops:
  UseCache: true
  TargetRubyVersion: 2.7.1
  Include:
    - bin/console
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - any_cache.gemspec

Layout/MultilineOperationIndentation:
  Enabled: false

# NOTE: for code clarity in tests
RSpec/LeakyConstantDeclaration:
  Enabled: false
