language: ruby
sudo: false
before_install: gem install bundler
cache: bundler
script:
- bundle exec rake rubocop
- bundle exec rake rspec
services:
  - redis-server
  - memcached
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.7
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.3.7
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.3.7
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.3.7
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.3.7
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.3.7
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.4.4
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.5.1
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
