language: ruby
sudo: false
before_install: gem install bundler
cache: bundler
script:
- bundle exec rspec
services:
- redis-server
- memcached
matrix:
  fast_finish: true
  include:
  - rvm: 2.3.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.4.9
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.5.7
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.6.5
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.3.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.4.9
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.5.7
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.6.5
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
notifications:
  slack:
    secure: CRYB00OjJTaAYDPM7VgzdU6kBu0WcgwxyzXR6UTrTklrz3jI8ZRKUxrIqNJXvvYbmQPmnRClCeb1/K865RaH+r6Lc+Fob9mBJrjX2eH8CRtBpn542MgKQcJrJR1rrZnxSq7hAfjzYddtbF/vlzkW5yIRLvtihzY9pP+o9XEJF4mhMZWZw8qeqfK16uDzInYpS7ocw7TjDobKPSpG7SXpm+tVMV+0Wmq/58GZDiHq/vEIPiEegnXEEA6lJao/isZtUGn0YFY+ibQA0MrjnBouIdm4MMkK62ybS8dV/EKT6z0ZuG81VhS8Jb6h8H5j9td8xzjYsHpb1FZE0Rwr8ClWmo2vPRekPxpwqJMBM9lBKJ4Ez7lNWsJP0YkleKfmDEN1KIaMMH4g2YXeTfDagVHc803ooNjCbS1EMA1fZgF77gdlG10sdbyexHkxYxw1rozSa1G6OdDBbKehdaCbqbiqx0unI6gQtENa6ouUiIndZjE/ehcHnP4Y8lFTIbwmvGqborkhsI/0/8X0/Xh6GDypOml3mvKT5u7m0UYBy5lSQpTpmZVz9TV3pId12DM1eObIeWxYRkz+L+7stQBfVAVy8mZFLxm2pmey/Vn5pwAnEwgOBZ5qFPrIEHrjgH91rpdvYVPYswYdGm7WrKPpta4pQhSqDMlKhW1zfk+AMmZ4Yz0=
