language: ruby
os: linux
dist: xenial
before_install: gem install bundler
cache: bundler
script:
- bundle exec rspec
services:
- redis
- memcached
jobs:
  fast_finish: true
  include:
  - rvm: 2.3.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_MEMORY_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support.gemfile
    env: TEST_AS_FILE_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_redis.gemfile
    env: TEST_AS_REDIS_CACHE_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/dalli.gemfile
    env: TEST_DALLI_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_STORE_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.4.10
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.5.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.6.6
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.7.1
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_DALLI_STORE=true
  - rvm: 2.3.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/redis_store.gemfile
    env: TEST_REDIS_CACHE=true
  - rvm: 2.3.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.4.10
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.5.8
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.6.6
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: 2.7.1
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
  - rvm: ruby-head
    gemfile: gemfiles/active_support_with_dalli.gemfile
    env: TEST_AS_MEM_CACHE_STORE_CACHE=true
